- includes/abstracts/abstract-wpum-form.php
There is no point of uploading the file before file checks are completed.
> Fixed file upload checks

- templates/form-fields/file-field.php
- templates/form-fields/file-uploaded.php
> Fix duplicated image markup fields when registration fails

- includes/wpum-forms/class-wpum-form-registration.php
Added do action 'wpum_before_registration_start' before the user registration process start
> Added do action 'wpum_before_registration_start'

- templates/form-fields/wysiwyg-field.php
Adds settings to the wysiwyg field
> Wysiwyg field settings

- includes/wpum-fields/types/class-wpum-field-repeater.php
- templates/form-fields/complex-field.php
@polevaultweb 
Resolves https://github.com/WPUserManager/wpum-custom-fields/issues/43
> #43 (wpum custom fields) repeater file field bug

- includes/actions.php
- includes/install.php
> #207 Installation not run on newly created subsite

- includes/actions.php
- includes/functions.php
- includes/wpum-admin/class-wpum-options-panel.php
> Added: frontend profile visibility control

- includes/filters.php
> Allow admins to prevent authentication method

- includes/actions.php
- includes/functions.php
- includes/wpum-fields/class-wpum-fields.php
- includes/wpum-fields/types/class-wpum-field-userrole.php
- templates/form-fields/userrole-field.php
Resolves WPUserManager/wpum-custom-fields#57
> Role field

- includes/functions.php
- includes/install.php
- includes/wpum-emails/wpum-email-functions.php
- includes/wpum-upgrades/class-wpum-plugin-updates.php
Resolves https://github.com/WPUserManager/wp-user-manager/issues/79
> Admin email for new user registration email now customizable

- includes/actions.php
- includes/filters.php
- includes/wpum-admin/class-wpum-options-panel.php
> added: new login settings and complete site lock

- includes/actions.php
- includes/wpum-database/class-wpum-db-fields-groups.php
- includes/wpum-database/class-wpum-db-fields.php
- includes/wpum-database/class-wpum-db-registration-forms.php
- includes/wpum-fields/class-wpum-fields-editor.php
- includes/wpum-forms/class-wpum-registration-forms-editor.php
> User values now updated when saving account form with an object cache.

- includes/abstracts/abstract-wpum-form.php
> #286 Messages template general-error.php customization not taking effect

- includes/functions.php
Resolves https://github.com/WPUserManager/wp-user-manager/issues/299
1.
> Upload fix

- includes/forms/class-wpum-form-password-recovery.php
Resolves https://github.com/WPUserManager/wp-user-manager/issues/317
1.
> 317 password reset message

- includes/fields/types/class-wpum-field-multicheckbox.php
Resolves https://github.com/WPUserManager/wpum-custom-fields/issues/74
@polevaultweb
Resolves #
1.
> Checkboxes not saving values

- includes/shortcodes/shortcodes.php
> Convert boolean value to string

- includes/roles/class-wpum-role.php
- includes/roles/class-wpum-roles-editor.php
> #338 - User Roles editor not saving capabilities properly

- includes/filters.php
> URLEncode the redirect query string

- includes/shortcodes/shortcodes.php
> Apostrophe in names not searchable through directory search
